// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5839.CRC2017test1.subsystems;

import org.usfirst.frc5839.CRC2017test1.RobotMap;
import org.usfirst.frc5839.CRC2017test1.commands.*;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveBase extends Subsystem {

    private final SpeedController frontleft = RobotMap.driveBaseFrontleft;
    private final SpeedController rearleft = RobotMap.driveBaseRearleft;
    private final SpeedController frontright = RobotMap.driveBaseFrontright;
    private final SpeedController rearright = RobotMap.driveBaseRearright;

    public void Drive(double x, double y, double z, double gyro) {
    	
    	
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {

    	setDefaultCommand(new DriveControl());
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

