// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5839.CRC2017test1.subsystems;

import org.usfirst.frc5839.CRC2017test1.RobotMap;
import org.usfirst.frc5839.CRC2017test1.commands.*;
import com.ctre.CANTalon;
import com.ctre.phoenix.motorcontrol.can.TalonSRX;

import edu.wpi.first.wpilibj.DigitalInput;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Gear extends Subsystem {

    private final TalonSRX gearintake = RobotMap.gearGearintake;
    private final TalonSRX gearlift = RobotMap.gearGearlift;
    private final DigitalInput switch1 = RobotMap.gearSwitch1;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void Liftstop() {
    	gearlift.set(0);
    }
    
    public void LiftGear() {
    	if (gearlift.getPosition() < 2700) {
			gearlift.set(null, 0.8);
		}else{
			gearlift.set(0);
		}
    }
    
    
    public void LowerGear() {
    	if (RobotMap.gearGearlift.isRevLimitSwitchClosed()) {
			gearlift.set(0);
		}else{
			gearlift.set(-0.5);
		}
    }
    
    public void LowerGear(double speed) {
    	if (RobotMap.gearGearlift.isRevLimitSwitchClosed()) {
			gearlift.set(0);
		}else{
			gearlift.set(-0.5);
		}
    }
    
    public void IntakeGear() {
    	gearintake.set(1);
    }
    
    public void GearOut() {
    	gearintake.set(-1);
    }
    
    public void GearStop() {
    	gearintake.set(0);
    }

    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

